declare const data: any;
declare const ai: any;
declare const sync: any;
declare const syncStatus: any;
declare const toast: any;
declare const workout: any;
declare const cardio: any;
declare const workoutEngine: any;
declare const workoutState: any;
declare const advicePanel: any;
declare const backup: any;
declare const appUpdate: any;
declare const pwaSupport: any;
declare const workoutReadiness: any;
declare const onboarding: any;
declare const theme: any;
declare const fooddb: any;
declare const storageMigrate: any;
declare const storageIdb: any;
declare const swipeActions: any;
declare const errorBus: any;
declare const miScalePure: any;
declare const miScaleBluetooth: any;
declare const aiJsonPure: any;

interface Window {
  data: any;
  ai: any;
  sync: any;
  syncStatus: any;
  toast: any;
  workout: any;
  cardio: any;
  workoutEngine: any;
  workoutState: any;
  advicePanel: any;
  backup: any;
  appUpdate: any;
  pwaSupport: any;
  workoutReadiness: any;
  onboarding: any;
  theme: any;
  fooddb: any;
  storageMigrate: any;
  storageIdb: any;
  swipeActions: any;
  errorBus: any;
  miScalePure: any;
  miScaleBluetooth: any;
  renderSafe: any;
  dataRecords: any;
  dataSchema: any;
  dataUtils: any;
  dataStore: any;
  dataUiState: any;
  dataHealthDiet: any;
  dataHealthWeight: any;
  dataHealthExercise: any;
  dataHealthProfile: any;
  dataGoalPlan: any;
  dataRoutinePlan: any;
  dataRoutineLibrary: any;
  dataHistoryView: any;
  healthSummaryPure: any;
  dataWeeklySummary: any;
  dataViews: any;
  dataTodayViewCore: any;
  dataAiTemplates: any;
  adviceTemplateManager: any;
  adviceAttachments: any;
  aiPricing: any;
  aiRoutingPure: any;
  aiJsonPure: any;
  aiModelCatalogPure: any;
  aiTaskSettings: any;
  syncPure: any;
  syncUi: any;
  syncAdapters: any;
  cardioPure: any;
  prTracker: any;
  volumeHeatmap: any;
  dataPlanAi: any;
  planAiPure: any;
  debugTools: any;
  aiDebug: any;
  backupRingPure: any;
  backupImportPure: any;
  loadAppScript: (name: string) => Promise<void>;
}
