declare const data: any;
declare const ai: any;
declare const sync: any;
declare const syncStatus: any;
declare const toast: any;
declare const workout: any;
declare const cardio: any;
declare const workoutEngine: any;
declare const workoutState: any;
declare const advicePanel: any;
declare const backup: any;
declare const appUpdate: any;
declare const onboarding: any;
declare const theme: any;
declare const fooddb: any;
declare const storageMigrate: any;
declare const storageIdb: any;
declare const swipeActions: any;
declare const errorBus: any;

interface Window {
  data: any;
  ai: any;
  sync: any;
  syncStatus: any;
  toast: any;
  workout: any;
  cardio: any;
  workoutEngine: any;
  workoutState: any;
  advicePanel: any;
  backup: any;
  appUpdate: any;
  onboarding: any;
  theme: any;
  fooddb: any;
  storageMigrate: any;
  storageIdb: any;
  swipeActions: any;
  errorBus: any;
  dataUtils: any;
  dataStore: any;
  dataUiState: any;
  dataHealthDiet: any;
  dataHealthWeight: any;
  dataHealthExercise: any;
  dataHealthProfile: any;
  dataGoalPlan: any;
  dataRoutineLibrary: any;
  dataHistoryView: any;
  dataWeeklySummary: any;
  dataViews: any;
  dataAiTemplates: any;
  aiPricing: any;
  syncPure: any;
  prTracker: any;
  volumeHeatmap: any;
}
